# Please fill in with your own data, please do not include port or database name in the url, if there is no password leave it blank.
database:
  url: "https://localhost"
  port: "3306"
  username: "admin"
  password: "password"
  database: "rlsmp"