name: ReverseLifeSMP
version: '${project.version}'
main: dev.awesomebfm.reverselifesmp.ReverseLifeSMP
api-version: 1.19
authors: [ AwesomeBFM ]
description: Survival Minecraft Plugin for the Reverse Life SMP
commands:
  hearts:
    description: Shows the amount of hearts you have
    usage: /hearts
  clearhearts:
    description: Clears a player's hearts
    usage: /clearhearts
    permission: reverselifesmp.admin
  resetdata:
    description: Resets the SMP data
    usage: /resetdata
    permission: reverselifesmp.admin
  undeathban:
    description: Un-death ban a player
    usage: /undeathban <player>
    permission: reverselifesmp.admin
  deathban:
    description: death ban a player
    usage: /deathban <player>
    permission: reverselifesmp.admin
permissions:
    rlsmp.admin:
        description: Allows access to all ReverseLifeSMP commands
        default: op
    rlsmp.default:
        description: Allows access to all ReverseLifeSMP commands
        default: true

